defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/project

version: 2
jobs:
  Checkout Code:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: npm ci
      - persist_to_workspace:
          root: .
          paths: [.]
  Check for vulnerabilities:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm audit --production
  Test node-10:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm t
      - persist_to_workspace:
          root: .
          paths:
            - .nyc_output
  Send Coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run report-coverage
      - store_artifacts:
          path: ./nyc_output
          prefix: coverage

  Build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: [.]

  Release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run semantic-release || true

workflows:
  version: 2
  Test build and deploy(master only):
    jobs:
      - Checkout Code
      - Check for vulnerabilities:
          requires:
            - Checkout Code
      - Test node-10:
          requires:
            - Checkout Code
      - Send Coverage:
          requires:
            - Test node-10
      - Build:
          requires:
            - Send Coverage
      - Release:
          requires:
            - Build
