defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/project

version: 2
jobs:
  Checkout Code:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run: npm ci
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: [node_modules]
      - persist_to_workspace:
          root: .
          paths: [.]
  Check for vulnerabilities:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm audit
  Test node-10:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm t
      - persist_to_workspace:
          root: .
          paths:
            - .nyc_output
  Send Coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run report-coverage
      - store_artifacts:
          path: ./nyc_output
          prefix: coverage

  Build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: [.]

  Release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run semantic-release || true

workflows:
  version: 2
  Test build and deploy(master only):
    jobs:
      - Checkout Code
      - Check for vulnerabilities:
          requires:
            - Checkout Code
      - Test node-10:
          requires:
            - Checkout Code
      - Send Coverage:
          requires:
            - Check for vulnerabilities
            - Test node-10
      - Build:
          requires:
            - Send Coverage
      - Release:
          requires:
            - Build
