defaults: &defaults

version: 2
jobs:
  Build and Test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm t
      - run: npm run report-coverage
      - store_artifacts:
          path: ./nyc_output
          prefix: coverage
      - run: npm run build
      - run: npm run semantic-release || true

workflows:
  version: 2
  Test build and deploy(master only):
    jobs:
      - Build and Test
