defaults: &defaults

version: 2
jobs:
  Build and Test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - restore_cache:
          keys:
            - dts-cache
      - run:
          name: Test
          command: npm t
      - save_cache:
          key: dts-cache
          paths:
            - ~/.dts

      - run:
          name: Send coverage
          command: npm run report-coverage
      - store_artifacts:
          path: ./nyc_output
          prefix: coverage

      - run:
          name: Build
          command: npm run build

      - run:
          name: Release
          command: npm run semantic-release || true

workflows:
  version: 2
  CI:
    jobs:
      - Build and Test
