name: Check cards data

on:
  workflow_dispatch:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: node scripts/update-cards.js
      - run: bash scripts/create-pr.bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
