name: CI

on:
  push:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.dts
          key: cache-dts

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm t
      - name: Send coverage
        run: npm run report-coverage
      - name: Build
        run: npm run build
      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npm run semantic-release
